# Generated by Django 2.2.6 on 2019-10-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('its', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='post_picture_alt',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
